# Generated by Django 3.2.9 on 2021-11-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
